### ISSUE TITLE
假开源项目，大家不要上当

### ISSUE THREAD

**Issue by yilianhuaixiao** [ecnice/flowable#14]
前端核心代码流程设计器是压缩后的文件，根本没有开源

--
<link href="/flow-bpmn-front/js/app.js" rel="preload" as="script"><link href="/flow-bpmn-front/js/chunk-vendors.js" rel="preload" as="script"></head>

**Comment by ecnice** [comment]
人都是这样子的，当你把很多东西都开源了的话，有那么一点点闭源，他就会说三到四，我也没有利用这个挣钱，我开源闭源又有什么关系呢？你着急什么，难道是你和相关人士有苟且之事发生。多为自己积累福报吧，饭可以随便吃，话不能随便讲，像你这样子的人，我不会跟你一般见识，我害怕你招雷劈的时候劈到了我，阿弥陀佛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ecnice/flow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月15日(星期一) 上午9:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ecnice/flow] 假开源项目，大家不要上当 (Issue #14)





 
前端核心代码流程设计器是压缩后的文件，根本没有开源
 
--
